### ISSUE TITLE
Provide an easy way for teams to create their own libraries and a basic robot template

### ISSUE THREAD

**Issue by noamzaks** [bazelRio/bazelRio#23]
In "an easy way for teams to create their own libraries" I mean some suggestion as to how you can store the '.so' or '.a' files online for C++ (or in the future store the jars for java).

The 'basic robot template' could be very similar to the original example, and possibly a "repo to fork" so teams can have their own robot template.

@connorworley @pjreiniger what do you think?

**Comment by pjreiniger** [comment]
I think the example (or maybe a second example, one vanilla and a[ crazier one](https://github.com/frc1678/robot-code-public) with a lot of external deps).

Work has indoctrinated me into "live at head", "build from source" and "monorepo". 

I would guess that the only people that are compiling c++ libraries for this arm processor are doing it explicitly for FIRST, so anything other than a vendor dep must be compiled from source anyway. Becuase of that, it would be useful to show examples of how to `new_git_repository` / `http_archive` the source into the workspace and build it. I don't know what kind of stuff C++ teams generally pull in, but maybe something like boost, protobuf, and gtest would be low hanging fruit.

If it is a library that you control, I think the recommendation should be to bazel-fy it. Either keep it a separate repository that can build independently with bazel and `new_/git_repository` it in, or embrace the monorepo and have it all in one spot

**Comment by noamzaks** [comment]
I was thinking about my team's use case (which I believe quite a few teams use as well). 

It includes a library with 'useful stuff' which is then used with robots.

I think to reduce compile times it might be beneficial for teams to be able to easily create '.a' or '.so' files and then use them in many projects

**Comment by pjreiniger** [comment]
The beauty of bazel is that its caching is incredible. Especially when you enable remote caching, and it is ungodly if you are smart enough to set up remote execution. When I was doing this for allwpilib and debugging mac builds through CI, remote caching took the build times down from an hour to less than 5 minutes.

With a monorepo (or, pulling in your library with with one of the repo tools) the first build would be slower. But assuming you don't change the library code, your iterative builds for that library will be (essentially) instantaneous.  

Compare this to if you have to pull them down from the cloud. You have to make your change, have no idea what it breaks, and publish it. Then, in your main repo, you have to update your deps, and likely cause a full rebuild anyway because the compiler will probably guess that the include path is dirty. You can short circuit this if you use submodules or have hooks for local publishing, but it still becomes a disjointed process.

**Comment by pjreiniger** [comment]
Is your code public?

**Comment by noamzaks** [comment]
> The beauty of bazel is that its caching is incredible. Especially when you enable remote caching, and it is ungodly if you are smart enough to set up remote execution. When I was doing this for allwpilib and debugging mac builds through CI, remote caching took the build times down from an hour to less than 5 minutes.

I see. Sounds awesome.

> Is your code public?

Not yet, but perhaps it will be
